### ISSUE TITLE
Use smart quotes

### ISSUE THREAD

**Issue by rapodaca** [rapodaca/dialect#100]
Quoted items are wrapped with double quotes. This looks bad when compiled to PDF because the left-hand quote is rendered as a right-hand smart quote.

To avoid this, use smart quotes:

```
``quotation''
```

**Comment by nbehrnd** [comment]
As a suggest -- if staying (La)TeX for the documentation -- [csquotes](https://www.ctan.org/pkg/csquotes) may be worth try, especially in conjunction with a `\usepackage[USenglish]{babel}` in the preamble of the `.tex`.

**Comment by rapodaca** [comment]
Good suggestion. Updated accordingly.
