### ISSUE TITLE
Polymer molecules

### ISSUE THREAD

**Issue by merkys** [rapodaca/dialect#31]
One of the most interesting incomplete features in the Daylight SMILES/OpenSMILES to me is the the polymer extension. Currently, SMILES are mostly used for nonpolymer molecules, but this ignores large set of chemical compounds.

I have explained the problem in https://github.com/timvdm/OpenSMILES/issues/8 and https://github.com/IUPAC/IUPAC_SMILES_plus/issues/9.

Thanks for an interesting and really much needed effort!

**Comment by rapodaca** [comment]
Polymer representation is an important problem, but beyond the scope of Dialect. Why not start a project to document an extension and provide a reference implementation?

**Comment by merkys** [comment]
Thanks for prompt response. Your suggestion sounds good, I will think about it. Closing the issue as beyond the scope of this project.
