### ISSUE TITLE
Stereodescriptors only valid on tetracoordinate atoms.

### ISSUE THREAD

**Issue by rapodaca** [rapodaca/dialect#33]
Discussion of stereo descriptors should indicate that it is an error to assign one to anything other than a tetracoordinate atom.

**Comment by johnmay** [comment]
Is ``C[S@](=O)CC`` tetracoordinate?

**Comment by johnmay** [comment]
Likewise ``C1[N@](O1)CC``

**Comment by rapodaca** [comment]
> Is `C[S@](=O)CC` tetracoordinate?

No, but it is tetravalent.

> Likewise `C1[N@](O1)CC`

No.

It may be a good idea to define the term, or just replace it with "an atom having four neighbors."
